modLoader="kotlinforforge"
loaderVersion="[1.15,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/Lumberjack/issues"

[[mods]]
    modId="lumberjack"
    version="1.0"
    displayName="Lumberjack"
	authors="ManApart"
    description='''
    Cut entire trees with one fell swoop
    '''
    credits="Trees collapse when chopped down"

[[dependencies.lumberjack]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"