modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory (26 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"

[[mods]]
    modId="lumberjack"
    version="1.0"
    displayName="Lumberjack"
	authors="ManApart"
    description='''
    Cut entire trees with one fell swoop
    '''
    credits="Trees collapse when chopped down" #optional

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"