modLoader="javafml"
loaderVersion="[26,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"

[[mods]]
    modId="lumberjack"
    version="1.0"
    displayName="Lumberjack"
	authors="ManApart"
    description='''
    Cut entire trees with one fell swoop
    '''
    credits="Trees collapse when chopped down"

[[dependencies.lumberjack]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"